tasks:
- init: sudo apt update -y && sudo apt upgrade -y && sudo apt install -y apktool && sudo apt install -y dexdump && sudo apt install -y ripgrep && virtualenv venv && source venv/bin/activate && python -m pip install --upgrade pip && pip install -r requirements.txt && python main.py
vscode:
  extensions:
    - ms-python.python
    - eamodio.gitlens
    - charliermarsh.ruff
    - SonarSource.sonarlint-vscode
