tasks:
- init: sudo apt update && sudo apt upgrade -y && sudo apt install -y apktool dexdump ripgrep && virtualenv venv && source venv/bin/activate && python -m pip install --upgrade pip wheel setuptools && pip install -r requirements.txt && python __init__.py
vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-python.black-formatter
    - eamodio.gitlens
    - charliermarsh.ruff
    - SonarSource.sonarlint-vscode
    - redhat.vscode-yaml
