tasks:
- init: sudo apt install -y dexdump && python -m pip install --upgrade pip && pip install -r requirements.txt
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - eamodio.gitlens