
name: "Code Scanning - Action"

on:
  push:
    branches: [main]
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '30 6 * * *'

jobs:
  CodeQL-Build:
    # CodeQL runs on ubuntu-latest, windows-latest, and macos-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: twfgcicdbot/TinyWeatherForecastGermanyMirror # see: https://github.com/actions/checkout/issues/24
          path: ./TinyWeatherForecastGermany
      
      - name: change Working directory
        run: cd ./TinyWeatherForecastGermany && ls -lisha
      
      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        # Override language selection by uncommenting this and choosing your languages
        with:
          languages: java
          paths: ./TinyWeatherForecastGermany

      # Autobuild attempts to build any compiled languages (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see below).
      #- name: Autobuild
      #  uses: github/codeql-action/autobuild@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      #- name: Validate Gradle wrapper
      #  uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./TinyWeatherForecastGermany/gradlew build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
