# This is a basic workflow to help you get started with Actions

name: exodus-privacy scan

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ ]
  schedule:
    - cron: "5 7 * * */2" # every two days at 7:05am UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  repository_dispatch: # run workflow on api request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: clone remote repo
        run: git clone https://github.com/twfgcicdbot/TinyWeatherForecastGermanyMirror TinyWeatherForecastGermanyMirror
          
      - name: clone this repo
        run: git clone https://github.com/twfgcicdbot/TinyWeatherForecastGermanyScan TinyWeatherForecastGermanyScan
      
      - name: update packages
        run: sudo apt-get update && sudo apt-get upgrade
      
      - name: Setup Python 3.x
        uses: actions/setup-python@v2.2.2
      
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      
      - name: install dexdump
        run: sudo apt-get install -y dexdump
      
      - name: install ripgrep
        run: sudo apt-get install -y ripgrep
      
      - name: install apktool
        run: sudo apt-get install -y apktool

      #- name: install brotli
      #  run: apt-get install brotli || true

      - name: install virtualenv
        run: pip install virtualenv
      
      - name: list directory contents
        run: ls -lisha
      
      - name: init virtualenv
        run: virtualenv venv
      
      - name: activate virtualenv
        run: source venv/bin/activate
      
      - name: list directory contents
        run: ls -lisha
      
      - name: install python requirements
        run: pip install -r TinyWeatherForecastGermanyScan/requirements.txt
      
      - name: run main.py
        run: python TinyWeatherForecastGermanyScan/main.py

      - name: run rg-pattern-search.py
        run: python TinyWeatherForecastGermanyScan/rg-pattern-search.py || true
      
      - name: run logtohtml.py
        run: python TinyWeatherForecastGermanyScan/logtohtml.py || true

      - name: list directory contents
        run: ls -lisha
      
      - name: list directory contents of TinyWeatherForecastGermanyScan
        run: cd TinyWeatherForecastGermanyScan && ls -lisha
      
      - name: return directory size
        run: du -sh

      - name: Archive analysis report and tracker signatures
        uses: actions/upload-artifact@v2
        with:
          name: reports-and-tracker-signatures
          path: |
            */*.json
            */*.md
            */*.html

      - name: Archive analysed apk
        uses: actions/upload-artifact@v2
        with:
          name: analysed-apk
          path: |
            */*.apk
      
      - name: list directory contents of TinyWeatherForecastGermanyScan
        run: cd TinyWeatherForecastGermanyScan && ls -lisha
      
      # also see here: https://github.community/t/support-for-pre-compressed-assets-and-brotli-compression/10605 
      #- name: compress assets using gzip and brotli
      #  run: |
      #    gzip -k -6 $(find TinyWeatherForecastGermanyScan -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$') || true
      #    find TinyWeatherForecastGermanyScan -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec brotli -f -k {} \; || true

      #- name: list directory contents of TinyWeatherForecastGermanyScan
      #  run: cd TinyWeatherForecastGermanyScan && ls -lisha
      
      - name: git push to origin
        run: |
          cd TinyWeatherForecastGermanyScan
          git config --global user.name 'twfgcicdbot'
          git config --global user.email 'twfgcicdbot@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git fetch --all
          git checkout --orphan 'gh-pages'
          git reset
          git add *.json
          git add *.md
          git add *.html
          git add BingSiteAuth.xml || true
          git add images/ || true
          git add sitemap.xml || true
          git add robots.txt || true
          git status
          git commit -m "update github pages"
          git push -f origin gh-pages
