# This is a basic workflow to help you get started with Actions

name: exodus-privacy scan

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - "5 7 * * *" # daily 7:05am UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: clone remote repo
        run: git clone https://github.com/twfgcicdbot/TinyWeatherForecastGermanyMirror
          
      - name: clone this repo
        run: git clone https://github.com/twfgcicdbot/TinyWeatherForecastGermanyScan
      
      - name: update packages
        run: sudo apt-get update && sudo apt-get upgrade
      
      - name: Setup Python 3.x
        uses: actions/setup-python@v2.2.2
      
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      
      - name: install dexdump
        run: sudo apt-get install dexdump
        
      - name: install virtualenv
        run: pip install virtualenv
      
      - name: list directory contents
        run: ls -lisha
      
      - name: init virtualenv
        run: virtualenv venv
      
      - name: activate virtualenv
        run: source venv/bin/activate
      
      - name: list directory contents
        run: ls -lisha
      
      - name: install python requirements
        run: pip install -r TinyWeatherForecastGermanyScan/requirements.txt
      
      - name: run main.py
        run: python TinyWeatherForecastGermanyScan/main.py
      
      - name: list directory contents
        run: ls -lisha
      
      - name: list directory contents of TinyWeatherForecastGermanyScan
        run: cd TinyWeatherForecastGermanyScan && ls -lisha
      
      - name: return directory size
        run: du -sh

      - name: Archive analysis report and tracker signatures
        uses: actions/upload-artifact@v2
        with:
          name: reports-and-tracker-signatures
          path: |
            */*.json
            */*.md
            */*.html

      - name: Archive analysed apk
        uses: actions/upload-artifact@v2
        with:
          name: analysed-apk
          path: |
            */*.apk
      
      - name: list directory contents of TinyWeatherForecastGermanyScan
        run: cd TinyWeatherForecastGermanyScan && ls -lisha
            
      - name: git push to origin
        run: |
          cd TinyWeatherForecastGermanyScan
          git config --global user.name 'twfgcicdbot'
          git config --global user.email 'twfgcicdbot@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git fetch --all
          git checkout --orphan 'gh-pages'
          git reset
          git add *.json
          git add *.md
          git add *.html
          git status
          git commit -m "update github pages"
          git push -f origin gh-pages
